### ISSUE TITLE
Answers and explanations

### ISSUE THREAD

**Issue by kamilogorek** [EastBayJS/javascript-puzzles#2]
It'd be great if everyone'd be able to read an answer to each puzzle with proper explanation why does it work that way.

**Comment by max-mapper** [comment]
good suggestion! @cspanring went through and wrote his solutions down and even left some comments, check out the network graph to see https://github.com/EastBayJS/javascript-puzzles/network

i'll add a note to the readme

**Comment by calvinmetcalf** [comment]
numbers 1 and 2 have multiple answers, compare [cspanring](https://github.com/cspanring/javascript-puzzles/blob/master/1.js) vs [jedireza](https://github.com/jedireza/javascript-puzzles/blob/master/1.js) for 1 and [jedireza](https://github.com/jedireza/javascript-puzzles/blob/master/2.js) vs [me](https://github.com/calvinmetcalf/javascript-puzzles/blob/master/2.js) in 2.

@jedireza has the better solution both times btw but neither would make a huge difference.
